# Generated by Django 2.0.1 on 2018-05-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0003_auto_20180513_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
